name: Test github workflows

on:
  push:
    branches:
      - "**"
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-jsp-env:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install graph-jsp-env
        run: |
          pip install graph-jsp-env
      - name: install win-unicode-console for the banners
        run: |
          pip install win-unicode-console

      - name: test importing it with powershell
        shell: pwsh
        run: |
          export PYTHONIOENCODING=UTF-8
          python -c "from graph_jsp_env.disjunctive_graph_jsp_env import DisjunctiveGraphJspEnv"
      - name: test importing it with bash
        shell: bash
        run: |
          export PYTHONIOENCODING=UTF-8
          python -c "from graph_jsp_env.disjunctive_graph_jsp_env import DisjunctiveGraphJspEnv"
